services:
  device-ingestion-service:
    image: ghcr.io/olivierlegendre/device-ingestion-service:v0.1.0
    restart: unless-stopped
    environment:
      APP_ENV: production
      SERVICE_NAME: device-ingestion-service
