services:
  reference-api-service:
    image: ghcr.io/olivierlegendre/reference-api-service:v0.2.0
    restart: unless-stopped
    environment:
      APP_ENV: production
      SERVICE_NAME: reference-api-service
